# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: ''
author_name: Test uppercase name
data_format: string
file_extension: ''
has_binder: false
has_settings: false
kind: server
labextension_name: test-uppercase
mimetype: ''
mimetype_name: ''
project_short_description: A JupyterLab extension with a Python module name containing
    some uppercase
python_name: Test-UpperCase
repository: https://github.com/gpelouze/jl-extension-template-bug-uppercase
test: true
viewer_name: ''

